name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
    - name: Install npm dependencies
      run: npm ci
    - name: Build the npm project
      run: npm run build
    - name: Copy .htaccess into dist
      run: cp .htaccess dist/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: static-website
        path: dist/

  deploy:
    name: Deploy via FTP
    needs: build
    runs-on: ubuntu-latest

    steps:
     steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: static-website
          path: ./dist
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.rubik.jakubsmutny.cz
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
