name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install npm dependencies
      run: npm install
    - name: Build the npm project
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: static-website
        path: dist/
